dist: xenial
language: php
services: docker

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6
  - 7.3

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=0

cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"

install:
- nvm install 12
- npm install
- composer install

script:
- npm run test